
name: Black and precommit

on: [push]


jobs:
  lint-and-fix-black:
    name: Lint and Fix
    runs-on: ubuntu-latest
    env:
      # Set an environment variable to select pip's cache directory for us to actually cache between runs.
      PIP_CACHE_DIR: /tmp/pip-cache-dir
      # The Python version your project uses. Feel free to change this if required.
      PYTHON_VERSION: 3.9
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: set python
        id: python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Restore pip cache
        uses: actions/cache@v2
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: "python-pip-${{ runner.os }}-\
          ${{ steps.python.outputs.python-version }}-\
          ${{ hashFiles('./Pipfile', './Pipfile.lock') }}"


      - name: install dev
        run: pip install -r dev-requirements.txt

      - name: install linter
        run: pip install black

      - name: lint-action
        uses: wearerequired/lint-action@v1.10.0
        with:
          black: true
          auto_fix: true

      - name: isort
        run: isort .

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Isort auto commit
          add_options: '-u'
          commit_options: --no-verify

      # Run precomit
      - name: Run hooks through our requirement file
        run: pre-commit run --all-files
        env:
          PIP_USER: 0

      - name: Discord Webhook
        uses: nebularg/actions-discord-webhook@v1.0.0
        if: always()
        with:
          webhook_url: ${{ secrets.BOT_UPDATES }}
          status: ${{ job.status }}
