
name: Black

on: [push]


jobs:
  lint-and-fix-black:
    name: Lint Action
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: set python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: install dev
        run: pip install -r dev-requirements.txt

      - name: install linter
        run: pip install black

      - name: isort
        run: isort .

      - name: debug
        run: git add .

      - name: lint-action
        uses: wearerequired/lint-action@v1.10.0
        with:
          black: true
          auto_fix: true

      - name: debug
        run: git status

      - name: Discord Webhook
        uses: nebularg/actions-discord-webhook@v1.0.0
        if: always()
        with:
          webhook_url: ${{ secrets.BOT_UPDATES }}
          status: ${{ job.status }}
